
// This file is automatically generated

export const METADATA = {
  "name": "react-native-openai-agents-js-agents",
  "version": "0.0.2",
  "versions": {
    "react-native-openai-agents-js-agents": "0.0.2",
    "openai": "^5.10.1"
  }
};

export default METADATA;
