
// This file is automatically generated

export const METADATA = {
  "name": "react-native-openai-agents-js-agents-openai",
  "version": "0.1.0",
  "versions": {
    "react-native-openai-agents-js-agents-openai": "0.1.0",
    "@openai/zod": "npm:zod@3.25.40 - 3.25.67",
    "openai": "^5.10.1"
  }
};

export default METADATA;
