
// This file is automatically generated

export const METADATA = {
  "name": "react-native-openai-agents-js-agents-extensions",
  "version": "0.1.0",
  "versions": {
    "react-native-openai-agents-js-agents-extensions": "0.1.0",
    "@openai/zod": "npm:zod@3.25.40 - 3.25.67"
  }
};

export default METADATA;
